In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from statsmodels.graphics.tsaplots import acf, plot_acf, plot_pacf
from statsmodels.tsa.stattools import acf, adfuller
from statsmodels.tsa.arima_model import ARMA, ARIMA

In [ ]:
df = pd.read_csv('/content/powerconsumption.csv')
df.head()

Datetime  Temperature  Humidity  WindSpeed  GeneralDiffuseFlows  \
0  1/1/2017 0:00        6.559      73.8      0.083                0.051   
1  1/1/2017 0:10        6.414      74.5      0.083                0.070   
2  1/1/2017 0:20        6.313      74.5      0.080                0.062   
3  1/1/2017 0:30        6.121      75.0      0.083                0.091   
4  1/1/2017 0:40        5.921      75.7      0.081                0.048   

   DiffuseFlows  PowerConsumption_Zone1  PowerConsumption_Zone2  \
0         0.119             34055.69620             16128.87538   
1         0.085             29814.68354             19375.07599   
2         0.100             29128.10127             19006.68693   
3         0.096             28228.86076             18361.09422   
4         0.085             27335.69620             17872.34043   

   PowerConsumption_Zone3  
0             20240.96386  
1             20131.08434  
2             19668.43373  
3             18899.27711  
4             18442.40964

In [ ]:
df.columns

Index(['Datetime', 'Temperature', 'Humidity', 'WindSpeed',
       'GeneralDiffuseFlows', 'DiffuseFlows', 'PowerConsumption_Zone1',
       'PowerConsumption_Zone2', 'PowerConsumption_Zone3'],
      dtype='object')

In [ ]:
df = df.set_index('Datetime')
df.head()

Temperature  Humidity  WindSpeed  GeneralDiffuseFlows  \
Datetime                                                               
1/1/2017 0:00        6.559      73.8      0.083                0.051   
1/1/2017 0:10        6.414      74.5      0.083                0.070   
1/1/2017 0:20        6.313      74.5      0.080                0.062   
1/1/2017 0:30        6.121      75.0      0.083                0.091   
1/1/2017 0:40        5.921      75.7      0.081                0.048   

               DiffuseFlows  PowerConsumption_Zone1  PowerConsumption_Zone2  \
Datetime                                                                      
1/1/2017 0:00         0.119             34055.69620             16128.87538   
1/1/2017 0:10         0.085             29814.68354             19375.07599   
1/1/2017 0:20         0.100             29128.10127             19006.68693   
1/1/2017 0:30         0.096             28228.86076             18361.09422   
1/1/2017 0:40         0.085             27335.69620             17872.34043   

               PowerConsumption_Zone3  
Datetime                               
1/1/2017 0:00             20240.96386  
1/1/2017 0:10             20131.08434  
1/1/2017 0:20             19668.43373  
1/1/2017 0:30             18899.27711  
1/1/2017 0:40             18442.40964

In [ ]:
df.index = pd.to_datetime(df.index)

In [ ]:
data = df

In [ ]:
data.head()

Temperature  Humidity  WindSpeed  GeneralDiffuseFlows  \
Datetime                                                                     
2017-01-01 00:00:00        6.559      73.8      0.083                0.051   
2017-01-01 00:10:00        6.414      74.5      0.083                0.070   
2017-01-01 00:20:00        6.313      74.5      0.080                0.062   
2017-01-01 00:30:00        6.121      75.0      0.083                0.091   
2017-01-01 00:40:00        5.921      75.7      0.081                0.048   

                     DiffuseFlows  PowerConsumption_Zone1  \
Datetime                                                    
2017-01-01 00:00:00         0.119             34055.69620   
2017-01-01 00:10:00         0.085             29814.68354   
2017-01-01 00:20:00         0.100             29128.10127   
2017-01-01 00:30:00         0.096             28228.86076   
2017-01-01 00:40:00         0.085             27335.69620   

                     PowerConsumption_Zone2  PowerConsumption_Zone3  
Datetime                                                             
2017-01-01 00:00:00             16128.87538             20240.96386  
2017-01-01 00:10:00             19375.07599             20131.08434  
2017-01-01 00:20:00             19006.68693             19668.43373  
2017-01-01 00:30:00             18361.09422             18899.27711  
2017-01-01 00:40:00             17872.34043             18442.40964

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 39190 entries, 2017-01-01 00:00:00 to 2017-09-30 03:30:00
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Temperature             39190 non-null  float64
 1   Humidity                39190 non-null  float64
 2   WindSpeed               39190 non-null  float64
 3   GeneralDiffuseFlows     39190 non-null  float64
 4   DiffuseFlows            39190 non-null  float64
 5   PowerConsumption_Zone1  39190 non-null  float64
 6   PowerConsumption_Zone2  39189 non-null  float64
 7   PowerConsumption_Zone3  39189 non-null  float64
dtypes: float64(8)
memory usage: 2.7 MB


In [ ]:
data

Temperature  Humidity  WindSpeed  GeneralDiffuseFlows  \
Datetime                                                                     
2017-01-01 00:00:00        6.559      73.8      0.083                0.051   
2017-01-01 00:10:00        6.414      74.5      0.083                0.070   
2017-01-01 00:20:00        6.313      74.5      0.080                0.062   
2017-01-01 00:30:00        6.121      75.0      0.083                0.091   
2017-01-01 00:40:00        5.921      75.7      0.081                0.048   
...                          ...       ...        ...                  ...   
2017-09-30 02:50:00       17.070      85.2      4.917                0.073   
2017-09-30 03:00:00       17.050      85.2      4.918                0.095   
2017-09-30 03:10:00       16.950      85.5      4.918                0.069   
2017-09-30 03:20:00       16.810      85.8      4.918                0.088   
2017-09-30 03:30:00       16.810      85.9      4.920                0.058   

                     DiffuseFlows  PowerConsumption_Zone1  \
Datetime                                                    
2017-01-01 00:00:00         0.119             34055.69620   
2017-01-01 00:10:00         0.085             29814.68354   
2017-01-01 00:20:00         0.100             29128.10127   
2017-01-01 00:30:00         0.096             28228.86076   
2017-01-01 00:40:00         0.085             27335.69620   
...                           ...                     ...   
2017-09-30 02:50:00         0.133             26894.86726   
2017-09-30 03:00:00         0.107             26786.54867   
2017-09-30 03:10:00         0.126             26843.89381   
2017-09-30 03:20:00         0.119             27047.78761   
2017-09-30 03:30:00         0.137             26907.60000   

                     PowerConsumption_Zone2  PowerConsumption_Zone3  
Datetime                                                             
2017-01-01 00:00:00             16128.87538             20240.96386  
2017-01-01 00:10:00             19375.07599             20131.08434  
2017-01-01 00:20:00             19006.68693             19668.43373  
2017-01-01 00:30:00             18361.09422             18899.27711  
2017-01-01 00:40:00             17872.34043             18442.40964  
...                                     ...                     ...  
2017-09-30 02:50:00             15825.77963             12973.23800  
2017-09-30 03:00:00             15747.19335             12890.86823  
2017-09-30 03:10:00             15807.06861             12843.79980  
2017-09-30 03:20:00             15735.96674             12867.33401  
2017-09-30 03:30:00                     NaN                     NaN  

[39190 rows x 8 columns]

In [ ]:
X1 = data['PowerConsumption_Zone3']

In [ ]:
X = X1[:500]

In [ ]:
size = int(len(X) * 0.66)
size

330

In [ ]:
X.squeeze()

Datetime
2017-01-01 00:00:00    20240.96386
2017-01-01 00:10:00    20131.08434
2017-01-01 00:20:00    19668.43373
2017-01-01 00:30:00    18899.27711
2017-01-01 00:40:00    18442.40964
                          ...     
2017-01-04 10:30:00    15250.12048
2017-01-04 10:40:00    15637.59036
2017-01-04 10:50:00    15805.30120
2017-01-04 11:00:00    15892.04819
2017-01-04 11:10:00    16117.59036
Name: PowerConsumption_Zone3, Length: 500, dtype: float64

In [ ]:
X

Datetime
2017-01-01 00:00:00    20240.96386
2017-01-01 00:10:00    20131.08434
2017-01-01 00:20:00    19668.43373
2017-01-01 00:30:00    18899.27711
2017-01-01 00:40:00    18442.40964
                          ...     
2017-01-04 10:30:00    15250.12048
2017-01-04 10:40:00    15637.59036
2017-01-04 10:50:00    15805.30120
2017-01-04 11:00:00    15892.04819
2017-01-04 11:10:00    16117.59036
Name: PowerConsumption_Zone3, Length: 500, dtype: float64

In [ ]:
train, test = X[0:size], X[size:len(X)]
history = [x for x in train]
predictions = list()

In [ ]:
# walk-forward validation
for t in range(len(test)):
	model = ARIMA(history, order=(1,1,1))
	model_fit = model.fit()
	output = model_fit.forecast()
	yhat = output[0]
	predictions.append(yhat)
	obs = test[t]
	history.append(obs)
	print('predicted=%f, expected=%f' % (yhat, obs))

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/arima_model.py:472: FutureWarning: 
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been deprecated in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and
statsmodels.tsa.SARIMAX. These will be removed after the 0.12 release.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained.

To silence this warning and continue using ARMA and ARIMA until they are
removed, use:

import warnings
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARMA',
                        FutureWarning)
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARIMA',
                        FutureWarning)

  warnings.warn(ARIMA_DEPRECATION_WARN, FutureWarning)


predicted=14251.443911, expected=14342.168670
predicted=14306.730714, expected=14122.409640
predicted=13921.787779, expected=13445.783130
predicted=12851.944758, expected=12595.662650
predicted=11910.719548, expected=11884.337350
predicted=11344.183827, expected=11624.096390
predicted=11478.064998, expected=11780.240960
predicted=11947.598388, expected=11838.072290
predicted=11852.439021, expected=11959.518070
predicted=12063.192465, expected=12167.710840
predicted=12334.954419, expected=12578.313250
predicted=12922.437388, expected=12861.686750
predicted=13052.731033, expected=13110.361450
predicted=13299.229914, expected=13353.253010
predicted=13537.465179, expected=13642.409640
predicted=13871.003690, expected=13885.301200
predicted=14062.484610, expected=14186.024100
predicted=14427.424157, expected=14110.843370
predicted=13989.598565, expected=14139.759040
predicted=14184.836486, expected=14521.445780
predicted=14863.572811, expected=14712.289160
predicted=14819.373899, expected=1

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
import matplotlib.pyplot as plt

In [ ]:
# evaluate forecasts
rmse = sqrt(mean_squared_error(test, predictions))
print('Test RMSE: %.3f' % rmse)

Test RMSE: 230.609


In [ ]:
predictions

[array([14251.44391128]),
 array([14306.73071434]),
 array([13921.78777865]),
 array([12851.94475763]),
 array([11910.71954817]),
 array([11344.18382745]),
 array([11478.06499818]),
 array([11947.59838783]),
 array([11852.43902123]),
 array([12063.19246542]),
 array([12334.95441911]),
 array([12922.43738823]),
 array([13052.73103284]),
 array([13299.22991409]),
 array([13537.46517912]),
 array([13871.00368987]),
 array([14062.4846096]),
 array([14427.42415742]),
 array([13989.5985654]),
 array([14184.83648603]),
 array([14863.57281111]),
 array([14819.37389902]),
 array([15222.90161179]),
 array([15064.50146822]),
 array([15414.84777098]),
 array([15487.15534211]),
 array([15845.70078886]),
 array([15985.24188222]),
 array([15921.06503782]),
 array([16135.09877553]),
 array([16135.13119045]),
 array([16451.03771245]),
 array([16418.82942265]),
 array([16482.95142261]),
 array([16769.00008597]),
 array([16661.94890628]),
 array([16907.21089125]),
 array([16464.7462996]),
 array([17167.5